### ISSUE TITLE
Is the artifact uploaded to maven central?

### ISSUE THREAD

**Issue by pedrovgs** [ecertic/otpsecure-android#1]
Hi @jgarcia-ecertic 😃 I'm trying to include the artifact as part of my app, but the library seems not to be uploaded to any artifacts repository. I've checked Maven Central and jcenter. Did you upload the artifact to any other repository?

**Comment by jgarcia-ecertic** [comment]
Hi @pedrovgs !

Not yet! we are waiting until having the first final version while getting the proper feedback by you karumi. 
As we usually work with our corporate artifactory we also need to set up Jenkins to push to Maven Central and develop the proper jenkins-file.
We'll let you know when it be pushed to Maven Central.

Many Thanks! :)

**Comment by pedrovgs** [comment]
👍 thanks!

**Comment by jgarcia-ecertic** [comment]
Hi @pedrovgs ,
the artifact has been uploaded to maven central sucessfully. Please check out the following URL

https://repo.maven.apache.org/maven2/com/ecertic/otpsecure/otpsecure-android/

Althought devops ecertic team has not yet finished to configure this project in Jenkins, we conseider these tasks are actually transparent to our consumers, so this ticket is being closed.

Thank you!
